dist: bionic
language: ruby
services:
  - docker
addons:
  apt:
    packages:
    - haveged # Extra entropy
before_install:
  - sudo service haveged start # Extra entropy to ensure quick start time for JRuby
  - rvm get master
  - rvm install jruby-9.2.13.0
  - rvm use jruby-9.2.13.0
  - gem install bundler -v '< 2'
  - docker-compose up -d
env:
  global:
    - JRUBY_OPTS='--client -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-Xss2m -Xcompile.invokedynamic=false'
script: bin/all_specs
notifications:
  email: false
